name: CI
on: push

jobs:
  lint:
    name: Run Linter check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
          run: npm ci

      - name: Run Lint
          run: npm run lint
  ci-server:
    name: CI Server
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm ci

      - name: Run Uint Tests
        run: npm test

  ci-client:
    name: CI Client
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install dependencies
        run: npm ci --prefix public/app

  build:
    name: Build Production
    runs-on: ubuntu-latest
    needs: [ci-server, ci-client]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Build
        run: npm run build



