name: Full-stack CI
on: push

jobs:
  full-stak-ci:
    name: Lint & Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1

      - name: Install Back-end dependencies
        run: npm ci

      - name: Build Full Projcet for Production
        run: npm run build
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}

      - name: Run Lint Check on Full Project
        run: npm run lint

      - name: Run Server Unit Tests Check
        run: npm test
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_SECRET: ${{ secrets.GOOGLE_SECRET }}
          GOOGLE_CALLBACK_URL: ${{ secrets.GOOGLE_CALLBACK_URL }}

      - name: Run Client Unit Tests Check
        run: npm test --prefix public/app
